version: '3.8'

services:
    skripsi-mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rahasia-root
        volumes:
            - ./data/mongo-data:/data/db
        ports:
            - 14001:27017
        networks:
            - skripsi-network
    skripsi-mariadb:
        image: mariadb:11
        environment:
            MARIADB_ROOT_PASSWORD: rahasia
            MARIADB_DATABASE: test
        ports:
            - '14002:3306'
        volumes:
            - ./data/mariadb-data:/var/lib/mysql
        networks:
            - skripsi-network
    skripsi-rabbitmq:
        image: rabbitmq:3
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        ports:
            - 5672:5672

networks:
    skripsi-network:
        driver: bridge
