version: '3.8'

services:
    skripsi-mongodb:
        image: mongo:7
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rahasia-root
        volumes:
            - ./data/mongo-data:/data/db
        ports:
            - '${MONGODB_PORT}'
        restart: unless-stopped
    skripsi-mariadb:
        image: mariadb:11
        environment:
            MARIADB_ROOT_PASSWORD: rahasia
            MARIADB_DATABASE: essay_scoring
            TZ: Asia/Jakarta
        ports:
            - '${MARIADB_PORT}'
        volumes:
            - ./data/mariadb-data:/var/lib/mysql
        restart: unless-stopped
    skripsi-rabbitmq:
        image: rabbitmq:3-management-alpine
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        ports:
            - '${RABIITMQ_PORT}'
            - 15672:15672
        volumes:
            - ./data/rabbitmq-data:/var/lib/rabbitmq
        restart: unless-stopped
    skripsi-redis:
        image: redis:7-alpine
        environment:
            REDIS_PASSWORD: my-password
            REDIS_PORT: 6379
        ports:
            - '${REDIS_PORT}'
        volumes:
            - ./data/redis-data:/var/lib/rabbitmq
            - ./data/redis-data:/root/redis
            - ./data/redis-dataredis.conf:/usr/local/etc/redis/redis.conf
        restart: unless-stopped

networks:
  default:
    name: nginx-proxy-manager_default
    external: true