version: '3.8'

services:
    skripsi-mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rahasia-root
        volumes:
            - ./data/mongo-data:/data/db
        ports:
            - 14001:27017
        networks:
            - skripsi-network
    skripsi-mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: rahasia
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: rahasia-user
        ports:
            - '14002:3306'
        volumes:
            - ./data/mysql-data:/var/lib/mysql
        networks:
            - skripsi-network
    skripsi-redis:
        image: redis/redis-stack-server:latest
        volumes:
            - ./data/redis-data:/data
        ports:
            - 14003:6379
        networks:
            - skripsi-network

networks:
    skripsi-network:
        driver: bridge
