version: '3.8'

services:
    skripsi-mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rahasia-root
        volumes:
            - ./data/mongo-data:/data/db
        ports:
            - 14001:27017
        networks:
            - skripsi-network
    skripsi-mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: rahasia
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: rahasia-user
        ports:
            - '14002:3306'
        volumes:
            - ./data/mysql-data:/var/lib/mysql
        networks:
            - skripsi-network
    skripsi-rabbitmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        ports:
            - 15672:15672
            - 5672:5672

networks:
    skripsi-network:
        driver: bridge
