version: '3.8'

services:
    skripsi-mongodb:
        image: mongo:7
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rahasia-root
        volumes:
            - ./data/mongo-data:/data/db
        ports:
            - "${MONGODB_PORT}"
        networks:
            - skripsi-network
    skripsi-mariadb:
        image: mariadb:11
        environment:
            MARIADB_ROOT_PASSWORD: rahasia
            MARIADB_DATABASE: essay-scoring
        ports:
            - "${MARIADB_PORT}"
        volumes:
            - ./data/mariadb-data:/var/lib/mysql
        networks:
            - skripsi-network
    skripsi-rabbitmq:
        image: rabbitmq:3-alpine
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        ports:
            - "${RABIITMQ_PORT}"
        volumes:
            - ./data/rabbitmq-data:/var/lib/rabbitmq
        networks:
            - skripsi-network

networks:
    skripsi-network:
        driver: bridge
