version: '3'
services:
    skripsi-fe:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        restart: unless-stopped

networks:
    default:
        name: nginx-proxy-manager_default
        external: true
