import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'InkWell - Auto Essay Scoring',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-surface'>
      <body className={nunito.className}>{children}</body>
    </html>
  )
}
