services:
  skripsi-ml:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      -  ./model/:/app/model/

networks:
    default:
        name: nginx-proxy-manager_default
        external: true
