version: '3'
services:
  skripsi-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    restart: unless-stopped

networks:
  default:
    name: skripsi-network
    external: true